### ISSUE TITLE
The num of entities in KGDataset.

### ISSUE THREAD

**Issue by faye0078** [usail-hkust/UUKG#4]
Thank you for your clear and well-documented code !

I built my own urbun graph and want to get graph embedding by your code(/UrbanKG_Embedding_Model). However, during the evaluation and ranking process, the val entity index exceeded the length of candidates entity.
 I discovered that the bug was caused by calculating 'max_axis' in kg_dataset.py using only the 'train' set. The 'val' set I divided contained entities that were not present in the 'train' set. This ultimately led to the bug. I use all data to init the 'max_axis', and the bug is fixed.

Is this correct? Or is it necessary to ensure that all entities present in the 'train' set ? Thank you for your response.

**Comment by yasNing** [comment]
Yes. When preparing dataset via _"kg_dataset.py"_, all data (i.e., train, val and test set) should be used to init the index. The obtained index file _"entity_idx_embedding.csv"_ will be further used to get embedding.

**Comment by faye0078** [comment]
Thank you for your answer !
